name: Build & Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build & Release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '5.0.x'

      - name: Get version
        id: vars
        run: |
            bash ./scripts/version.sh
            echo "version=$(cat version.txt)" >> $GITHUB_OUTPUT
  
      - name: Build
        env:
            SOLUTIONFILE: FiltexNet.sln
            VERSION: ${{ steps.vars.outputs.version }}
        run: |
          bash ./scripts/build.sh

      - name: Test
        env:
            SOLUTIONFILE: FiltexNet.sln
        run: |
          bash ./scripts/test.sh

      - name: Create release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ steps.vars.outputs.version }}"
          release_name: "v${{ steps.vars.outputs.version }}"
          draft: false
          prerelease: false

      - name: Pack
        env:
            NUGET_SOURCE: https://api.nuget.org/v3/index.json
            NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
            VERSION: ${{ steps.vars.outputs.version }}
        run: |
            bash ./scripts/pack.sh